empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'departamento/',
        views.Pruebaview.as_view()
        ),
    path(
        'new_departamento/',
        views.NewDepartamentoView.as_view(),
        name="nuevo_departamento"
        ),
    path(
        'listar_departamentos/',
        views.DepartamentoListView.as_view(),
        name="listar-departamentos"
    ),
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from applications.persona import views


app_name = "persona_app"

urlpatterns = [
    path(
        'persona/', 
        views.Pruebaview.as_view()
        ),
    path(
        'listar-empleados/', 
        views.ListAllEmpleados.as_view(),
        name="empleados_all"
        ),
    path(
        'empleados-admin/',
        views.ListAllEmpleadosAdmin.as_view(),
        name="empleados_admin"
        ),
    path(
        'editar-empleado/<pk>',
        views.EmpleadoUpdateView.as_view(),
        name="editar_empleado"
    ),
    # Listar segun palabra clave
    path(
        'listar-filtro/<shotname>', 
        views.ListByAreaEmpleado.as_view(),
        name="empleados_area"
        ),
    path(
        'buscar-empleado/', 
        views.ListEmpleadoByKword.as_view()
        ),
    path(
        'habilidades/', 
        views.ListHabilidadesEmpleado.as_view()
        ),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name="empleado_detalle"
        ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name="empleado_add"
        ),
    path(
        'success/', 
        views.SuccesView.as_view(), 
        name = "exito",
        ),
    path(
        'delete-empleado/<pk>',
        views.EmpleadoDeleteView.as_view(),
        name="eliminar_empleado",
        ),
    path(
        '',
        views.InicioView.as_view(), name="inicio"
        ),
    
]

empleado/empleado/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include

# IMPORTACIONES necesarias para podes mostrar los archivos MEDIA
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/templates/includes/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body>
    {% block content %}
    {% endblock content %}
    
    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
        $(document).foundation();
    </script>
</body>
</html>

empleado/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text">Empleados</li>
            <li><a href="{% url 'persona_app:empleados_all' %}">Listar</a></li>
            <li><a href="{% url 'departamento_app:listar-departamentos' %}">Departamentos</a></li>
            <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
            <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Agregar Departamento</a></li>
        </ul>
    </div>
    <div class="top-bar-right">
            <ul class="menu">
            <li><input type="search" placeholder="Buscar Empleado"></li>
            <li><a href="{% url 'persona_app:empleado_add' %}" class="button">Registrar Nuevo</a></li>
        </ul>
    </div>
</div>