empleado/applications/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('lista/', views.PruebaListView.as_view()),
    path('lista-prueba/', views.ListarPrueba.as_view()),
    path('add/', views.PruebaCreateView.as_view(), name="prueba_add"),
    path('resume/', views.ResumeFoundationView.as_view(), name="resume"),
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from applications.persona import views


app_name = "persona_app"

urlpatterns = [
    path(
        'persona/', 
        views.Pruebaview.as_view()
        ),
    path(
        'listar-empleados/', 
        views.ListAllEmpleados.as_view(),
        name="empleados_all"
        ),
    path(
        'empleados-admin/',
        views.ListAllEmpleadosAdmin.as_view(),
        name="empleados_admin"
        ),
    path(
        'editar-empleado/<pk>',
        views.EmpleadoUpdateView.as_view(),
        name="editar_empleado"
    ),
    # Listar segun palabra clave
    path(
        'listar-filtro/<shotname>', 
        views.ListByAreaEmpleado.as_view(),
        name="empleados_area"
        ),
    path(
        'buscar-empleado/', 
        views.ListEmpleadoByKword.as_view()
        ),
    path(
        'habilidades/', 
        views.ListHabilidadesEmpleado.as_view()
        ),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name="empleado_detalle"
        ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name="empleado_add"
        ),
    path(
        'success/', 
        views.SuccesView.as_view(), 
        name = "exito",
        ),
    path(
        'delete-empleado/<pk>',
        views.EmpleadoDeleteView.as_view(),
        name="eliminar_empleado",
        ),
    path(
        '',
        views.InicioView.as_view(), name="inicio"
        ),
    
]

empleado/empleado/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include

# IMPORTACIONES necesarias para podes mostrar los archivos MEDIA
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/home/models.py
from django.db import models

class Prueba(models.Model):
    titulo = models.CharField(max_length=255)
    subtitulo = models.CharField(max_length=50)
    cantidad = models.IntegerField()
    
    def __str__(self):
        return self.titulo + ".........." + self.subtitulo
    

empleado/applications/persona/models.py
from email.policy import default
from re import T
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField


class Habilidades(models.Model):
    habilidad = models.CharField("Habilidad", max_length=50)

    class Meta:
        verbose_name = "Hablidad"
        verbose_name_plural = "Habilidades Empleados"

    def __str__(self):
        return str(self.id) + "--" + self.habilidad



class Empleado(models.Model):
    """ Modelo para Tabla Empleado"""
    job_choices = (
            ("1", "CONTADOR"),
            ("2", "ADMINISTRADOR"),
            ("3", "ECONOMISTA"),
            ("4", "OTRO"))
    
    first_name = models.CharField("Nombre", max_length=60)
    last_name = models.CharField("Apellidos", max_length=50)
    full_name = models.CharField("Nombre Completo", max_length=120, blank=True)
    job = models.CharField("Trabajo", choices=job_choices, max_length=1)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    image = models.ImageField("Imagen", upload_to="empleado", blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Persona'
        verbose_name_plural = 'Personal'
        ordering = ["first_name" , "last_name"]


    def __str__(self):
        return str(self.id) + "--" + self.first_name + "--" + self.last_name

empleado/applications/home/forms.py
from logging import PlaceHolder
from django import forms
from .models import Prueba



class PruebaForm(forms.ModelForm):
    """Form definition for Prueba."""

    class Meta:
        """Meta definition for Pruebaform."""

        model = Prueba
        fields = (
            "titulo",
            "subtitulo",
            "cantidad",
            )

        widgets = {
            "titulo": forms.TextInput (attrs= { "PlaceHolder": "ingrese texto aqui--"})
        }

    # validacion de datos en el form, antes de enviar datos
    def clean_cantidad(self):
        cantidad = self.cleaned_data.get('cantidad')
        if cantidad < 10:
            raise forms.ValidationError("Ingrese un numero mayor a 10")
        return cantidad

empleado/applications/persona/forms.py
from tkinter import Widget
from django import forms
from .models import Empleado, Habilidades

class EmpleadoForm(forms.ModelForm):
    """Form definition for Empleado."""

    class Meta:
        """Meta definition for Empleadoform."""
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'image',
            'habilidades',
            )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

empleado/applications/home/views.py
from django.db.models import fields
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, TemplateView

from .forms import PruebaForm
from .models import Prueba



""" *** Aplicacion para pruebas *** """

class PruebaListView(ListView):
    template_name = "home/lista.html"
    # Parametro para envio de datos
    context_object_name = "listaNumeros"
    queryset = ["1", "10", "20", "30", "555"]


class ListarPrueba(ListView):
    template_name = "home/lista_prueba.html"
    model = Prueba
    context_object_name = "lista"


class PruebaCreateView(CreateView):
    template_name = "home/add.html"
    model = Prueba
    # ver la validacion en el archivo forms.py
    form_class = PruebaForm
    success_url = reverse_lazy("persona_app:exito")


class ResumeFoundationView(TemplateView):
    template_name = "home/resume_foundation.html"

empleado/applications/persona/views.py
from dataclasses import fields
from multiprocessing import context
from operator import mod
from sre_constants import SUCCESS
from statistics import mode

from applications.departamento.models import Departamento
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView, TemplateView, UpdateView)

# Forms
from .forms import EmpleadoForm
# Models
from .models import Empleado

# DOCUMENTACION DE VISTAS GENERICAS
# https://ccbv.co.uk/

# TEMPLATE VIEW
class Pruebaview(TemplateView):
    """ Vista a pagina de prueba

    Args:
        TemplateView ():
    """
    template_name = "home/persona.html"


class ListAllEmpleados(ListView):
    """ Vista que muestra empleados por filtro de full_name

    Args:
        full_name

    Returns:
        empleados (object), con pagination
    """
    template_name = "persona/list_all.html"
    paginate_by = 4
    # Al usar paginacion, automaticamente se crea un objeto llamado "page_obj" que sirve para identificar los numeros de pagina y navegar
    ordering = "id"
    context_object_name = "empleados"

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword1",'')
        lista = Empleado.objects.filter(full_name__icontains=palabra_clave)
        return lista


class ListAllEmpleadosAdmin(ListView):
    """ Vista que muestra todos los empleados y permite edicion 

    Returns:
        empleados (object), con pagination
    """
    template_name = "persona/lista_empleados.html"
    paginate_by = 4
    ordering = "id"
    context_object_name = "empleados"
    model = Empleado


class ListByAreaEmpleado(ListView):
    """ Vista que muestra empleados segun departamento

    Args:
        area

    Returns:
        empleados (object), con pagination
    """
    template_name = "persona/list_filtro.html"

    def get_queryset(self):
        area = self.kwargs['shotname']
        queryset = Empleado.objects.filter(departamento__shot_name = area)
        return queryset

    context_object_name = "empleados"


class ListEmpleadoByKword(ListView):
    """ Vista que muestro empleado particular por nombre

    Args:
        first_name

    Returns:
        empleados (object)
    """
    template_name = "persona/by_kword.html"
    context_object_name = "empleados"
    
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword1",'')
        lista = Empleado.objects.filter(first_name = palabra_clave)
        return lista


# DETAIL VIEW
class EmpleadoDetailView(DetailView):
    """ Vista que muestra detalle de empleado segun PK

    Args:
        pk = ID

    Returns:
        emple (object)
    """
    model = Empleado
    template_name = "persona/detail_empleado.html"
    context_object_name = "emple"
    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context["titulo"] = "EL TITULO QUE ASIGNE SOBREESCRIBIENDO"
        return context


# TEMPLATE VIEW 
class SuccesView(TemplateView):
    """ Vista de Exito"""
    template_name = "persona/success.html"


# CREATE VIEW
class EmpleadoCreateView(CreateView):
    """ Vista para registrar nuevo empleado """
    template_name = "persona/add.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy("persona_app:empleados_admin")
    
    def form_valid(self, form):
        empleado = form.save()
        empleado.full_name = empleado.first_name + " " + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


# UPDATE VIEW
class EmpleadoUpdateView(UpdateView):
    """ Vista para actualizar datos de un empleado en particular """
    template_name = "persona/update.html"
    model = Empleado
    fields = [
        "first_name",
        "last_name",
        "job",
        "departamento",
        "habilidades",
    ]
    success_url = reverse_lazy("persona_app:empleados_admin")
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)


# DELETE VIEW 
class EmpleadoDeleteView(DeleteView):
    """ Vista para eliminar empleado """
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy("persona_app:empleados_admin")
    object_context_name = "empleado"


class InicioView(TemplateView):
    """ Vista de pagina de Inicio """
    template_name = "persona/inicio.html"

empleado/templates/persona/add.html
{% extends 'includes/base.html' %}


{% block title %}
    Registrar Empleado
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell"> Registrar Empleado </h1>
            <form method="post" class="cell grid-x grid-margin-x" enctype="multipart/form-data"> {% csrf_token %}
                <div class="cell large-6">
                    <label>
                        Nombres:
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>
                        Apellidos:
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>
                        Trabajo:
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>
                        Area:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>
                        Habilidades Extras:
                        {{ form.habilidades }}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>
                        FOTO:
                        {{ form.image }}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">
                        Crear
                    </button>
                </div>
            </form>
        </div>
    </div>

    {% endblock content %}
    
<h1> Registrar persona </h1>

<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Subir datos </button>
</form>

empleado/templates/persona/by_kword.html
<h1>BUSCAR EMPLEADOS POR PALABRA CLAVE</h1>


<form method="GET"> {% csrf_token %}
    <input type="text" id="kword" name="kword1" placeholder="ingrese nombre aqui">
    <button type="submit"> Buscar </button>
</form>

LISTA DE EMPLEADOS FILTRADOS
<ul>
    {% for i in empleados %}
        <li>{{ i }}</li>
    {% endfor %}
</ul>

empleado/templates/persona/delete.html
{% extends 'includes/base.html' %}


{% block title %}
    Eliminar Empleado
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h2 class="cell"> Eliminar empleado: {{empleado.first_name }} {{empleado.last_name}} </h1>
            <form class="cell" method="post"> {% csrf_token %}
                <div class="callout secondary">
                    <h5> Desea eliminar este empleado? </h5>
                    <button class="alert button" type="submit"> Confirmar </button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

empleado/templates/persona/detail_empleado.html
{% extends 'includes/base.html' %}
{% load static %}

{% block title %}
    {{ object.full_name }}
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="cell large-4 card" style="width: 300px;">
                <div class="card-divider">
                    {{ object.get_job_display }}
                </div>
                
                {% if object.image %}
                    <img src="{{ object.image.url }}"> 
                {% else %}
                    <img src="{% static 'img/persona/defecto.png' %}">    
                {% endif %}
                
                <div class="card-section">
                    <h4>{{ object.full_name }}</h4>
                    <p>{{ object.first_name }} </p>
                    <p>{{ object.last_name }} </p>
                    <p>{{ object.departamento.shot_name }} </p>
                    <p><span class="label"> Habilidades </span></p>
                    <ul class="vartical-menu">
                        
                        {% for hab in object.habilidades.all %}
                            <li>{{ hab.habilidad }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

empleado/templates/persona/habilidades.html
<h1> Habilidades </h1>

{{ habilidades }}


<ul>
    
    {% for habilidad in  habilidades %}
        {{ habilidad }}
    {% endfor %}
    
</ul>

empleado/templates/persona/home.html
<h1> ESTE ES EL HOME DE PERSONA</h1>

empleado/templates/persona/inicio.html
{% extends "includes/base.html" %}
{% load static %}

{% block title%}
    agina de inicio sistema de empleados
{% endblock title%}


{% block content %}

    {% include "includes/header.html" %}

<!-- INICIO de la imagen de portada -->

    <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
        <div class="orbit-wrapper">
            <div class="orbit-controls">
                <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
                <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
            </div>
            <ul class="orbit-container">
                <li class="is-active orbit-slide">
                    <figure class="orbit-figure">
                        <img class="orbit-image" src= "{% static 'img/persona/grupo1.jpg' %}" alt="Personas">
                        <figcaption class="orbit-caption">Space, the final frontier.</figcaption>
                    </figure>
                </li>
                <li class="orbit-slide">
                    <figure class="orbit-figure">
                        <img class="orbit-image" src="{% static 'img/persona/grupo2.jpg' %}" alt="Brindis">
                        <figcaption class="orbit-caption">Lets Rocket!</figcaption>
                    </figure>
                </li>
            </ul>
        </div>
    </div>
<!-- FIN imagen de la portada-->

<!-- INICIO Bloque de Bienvenida -->
    <div class="grid-x align-center">
        <h1 class="cell large-8" style="font-size: 20px; text-align: center;"> Bienvenido al Sistema de Registro de Empleados </h1>
        <div class="cell large-7">
            <div class="callout success">
                <h5>Registra y Controla Empleados</h5>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nesciunt incidunt adipisci reprehenderit delectus nostrum tenetur possimus obcaecati, vitae soluta sapiente pariatur vero ducimus eius sed repellendus facere nobis? Explicabo, iusto.</p>
                <a href="#">Ver Empleados</a>
            </div>
        </div>
    </div>
<!-- FIN Bloque de Bienvenida -->

{% endblock content%}

empleado/templates/persona/list_all.html
{% extends 'includes/base.html' %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword1" placeholder="Buscar Empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="submit success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="100">ID</th>
                        <th width="150">Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for elemento in empleados %}
                        <tr>
                            <td>{{ elemento.id }}</td>
                            <td>{{ elemento.first_name }}</td>
                            <td>{{ elemento.last_name }}</td>
                            <td>{{ elemento.departamento }}</td>
                            <td> <a href="{% url 'persona_app:empleado_detalle' elemento.id %}" class="button warning"> Ver Mas </a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">

                        {% if page_obj.has_previous %}
                            <li class="pagination-previous"> 
                                <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
                            </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}
                            {% if pagina ==  page_obj.number %} 
                                <li class="current">
                                    <span class="show-for-sr">You're on page</span> {{ pagina }}
                                </li>
                            {% else %}
                                <li>
                                    <a href="?page={{pagina}}"> {{ pagina }} </a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                            </li>
                        {% endif %}

                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

empleado/templates/persona/list_filtro.html
{% extends 'includes/base.html' %}

{% block title %}
    Personas en departamento especifico
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <div class="cell"><h1>Empleados por Area: </h1> </div>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="100">ID</th>
                            <th width="150">Nombres</th>
                            <th width="150">Apellidos</th>
                            <th width="150">Departamento</th>
                            <th width="150">Accion</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for elemento in empleados %}
                            <tr>
                                <td>{{ elemento.id }}</td>
                                <td>{{ elemento.first_name }}</td>
                                <td>{{ elemento.last_name }}</td>
                                <td>{{ elemento.departamento }}</td>
                                <td> <a href="{% url 'persona_app:empleado_detalle' elemento.id %}" class="button warning"> Ver Mas </a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}

empleado/templates/persona/lista_empleados.html
{% extends 'includes/base.html' %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista de Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="100">ID</th>
                        <th width="150">Nombres</th>
                        <th width="150">Apellidos</th>
                        <th width="150">Departamento</th>
                        <th width="150">Accion</th>
                    </tr>
                </thead>
                <tbody>
                    {% for empleado in empleados %}
                        <tr>
                            <td>{{ empleado.id }}</td>
                            <td>{{ empleado.first_name }}</td>
                            <td>{{ empleado.last_name }}</td>
                            <td>{{ empleado.departamento }}</td>
                            <td> 
                                <a href="{% url 'persona_app:editar_empleado' empleado.id %}" class="button warning"> EDITAR </a>
                                <a href="{% url 'persona_app:eliminar_empleado' empleado.id %}" class="button alert"> ELIMINAR </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">

                        {% if page_obj.has_previous %}
                            <li class="pagination-previous"> 
                                <a href="?page={{page_obj.previous_page_number}}">Anterior</a>
                            </li>
                        {% endif %}

                        {% for pagina in paginator.page_range %}
                            {% if pagina ==  page_obj.number %} 
                                <li class="current">
                                    <span class="show-for-sr">You're on page</span> {{ pagina }}
                                </li>
                            {% else %}
                                <li>
                                    <a href="?page={{pagina}}"> {{ pagina }} </a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                            </li>
                        {% endif %}

                    </ul>
                </nav>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

empleado/templates/persona/success.html
<h1> CARGADO CON EXITO!</h1>

<h3>reverse lazy: persona_app:exito</h3>

empleado/templates/persona/update.html
{% extends 'includes/base.html' %}


{% block title %}
    Editar Empleado
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Modificar Empleado</h1>
            <div class="cell">
                <form method=POST class="grid-x"> {% csrf_token %}
                    <div class="cell large-6">
                        <label>
                            Nombres:
                            {{ form.first_name }}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>
                            Apellidos:
                            {{ form.last_name }}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>
                            Trabajo:
                            {{ form.job }}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>
                            Area:
                            {{ form.departamento }}
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label>
                            Habilidades Extras:
                            {{ form.habilidades }}
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="success button">
                            Guardar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>




{% endblock content %}