empleado/applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "departamento_app"

urlpatterns = [
    path(
        'departamento/',
        views.Pruebaview.as_view()
        ),
    path(
        'new_departamento/',
        views.NewDepartamentoView.as_view(),
        name="nuevo_departamento"
        ),
    path(
        'listar_departamentos/',
        views.DepartamentoListView.as_view(),
        name="listar-departamentos"
    ),
]

empleado/applications/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('lista/', views.PruebaListView.as_view()),
    path('lista-prueba/', views.ListarPrueba.as_view()),
    path('add/', views.PruebaCreateView.as_view(), name="prueba_add"),
    path('resume/', views.ResumeFoundationView.as_view(), name="resume"),
]

empleado/applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from applications.persona import views


app_name = "persona_app"

urlpatterns = [
    path(
        'persona/', 
        views.Pruebaview.as_view()
        ),
    path(
        'listar-empleados/', 
        views.ListAllEmpleados.as_view(),
        name="empleados_all"
        ),
    path(
        'empleados-admin/',
        views.ListAllEmpleadosAdmin.as_view(),
        name="empleados_admin"
        ),
    path(
        'editar-empleado/<pk>',
        views.EmpleadoUpdateView.as_view(),
        name="editar_empleado"
    ),
    # Listar segun palabra clave
    path(
        'listar-filtro/<shotname>', 
        views.ListByAreaEmpleado.as_view(),
        name="empleados_area"
        ),
    path(
        'buscar-empleado/', 
        views.ListEmpleadoByKword.as_view()
        ),
    path(
        'habilidades/', 
        views.ListHabilidadesEmpleado.as_view()
        ),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name="empleado_detalle"
        ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name="empleado_add"
        ),
    path(
        'success/', 
        views.SuccesView.as_view(), 
        name = "exito",
        ),
    path(
        'delete-empleado/<pk>',
        views.EmpleadoDeleteView.as_view(),
        name="eliminar_empleado",
        ),
    path(
        '',
        views.InicioView.as_view(), name="inicio"
        ),
    
]

empleado/empleado/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include

# IMPORTACIONES necesarias para podes mostrar los archivos MEDIA
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/applications/departamento/models.py
from django.db import models

class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shot_name = models.CharField('Nombre_Corto', max_length=20)
    anulate = models.BooleanField('anulado', default = False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la Empresa'
        ordering = ["id"]

    def __str__(self):
        return str(self.id) + ' - ' + self.name + ' - ' + self.shot_name

empleado/applications/home/models.py
from django.db import models

class Prueba(models.Model):
    titulo = models.CharField(max_length=255)
    subtitulo = models.CharField(max_length=50)
    cantidad = models.IntegerField()
    
    def __str__(self):
        return self.titulo + ".........." + self.subtitulo
    

empleado/applications/departamento/forms.py
from django import forms



class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellido = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shortname = forms.CharField(max_length=50)

empleado/applications/home/forms.py
from logging import PlaceHolder
from django import forms
from .models import Prueba



class PruebaForm(forms.ModelForm):
    """Form definition for Prueba."""

    class Meta:
        """Meta definition for Pruebaform."""

        model = Prueba
        fields = (
            "titulo",
            "subtitulo",
            "cantidad",
            )

        widgets = {
            "titulo": forms.TextInput (attrs= { "PlaceHolder": "ingrese texto aqui--"})
        }

    # validacion de datos en el form, antes de enviar datos
    def clean_cantidad(self):
        cantidad = self.cleaned_data.get('cantidad')
        if cantidad < 10:
            raise forms.ValidationError("Ingrese un numero mayor a 10")
        return cantidad

empleado/applications/departamento/views.py
from applications import departamento
from applications.persona.models import Empleado
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import FormView

from .forms import NewDepartamentoForm
from .models import Departamento


class Pruebaview(TemplateView):
    """ Muestra todos los departamentos

    Args:
        TemplateView ():
    """
    template_name = "departamento/home.html"


class NewDepartamentoView(FormView):
    """ Vista para Crear nuevos Departamentos

    Args:
        Recibe formulario del html

    Returns:
        Form
    """
    template_name = "departamento/new_departamento.html"
    # Se usa form_class para recibir datos
    form_class = NewDepartamentoForm
    success_url = reverse_lazy("persona_app:exito")
    
    def form_valid(self, form):
        """
        departamento = form.cleaned_data["departamento"]
        shortname = form.cleaned_data["shortname"]
        Departamento.objects.create(
            name = departamento
            shot_name = shortname 
        )
        """
        # FORMA ALTERNATIVA DE CREAR ESTO (lo de arriba)
        depa = Departamento(
            name = form.cleaned_data["departamento"],
            shot_name = form.cleaned_data["shortname"],
        )
        depa.save()

        nombre = form.cleaned_data["nombre"]
        apellido = form.cleaned_data["apellido"]
        # Crear segun ORM de django
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = "1",
            departamento = depa,
        )
        return super(NewDepartamentoView,self).form_valid(form)


class DepartamentoListView(ListView):
    """ Muestra todos los departamentos y se puede ver los empleados que hay dentor de cada uno desde el detail

    Args:
        ListView (_type_): _description_
    """
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = "departamentos"

empleado/applications/home/views.py
from django.db.models import fields
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, TemplateView

from .forms import PruebaForm
from .models import Prueba



""" *** Aplicacion para pruebas *** """

class PruebaListView(ListView):
    template_name = "home/lista.html"
    # Parametro para envio de datos
    context_object_name = "listaNumeros"
    queryset = ["1", "10", "20", "30", "555"]


class ListarPrueba(ListView):
    template_name = "home/lista_prueba.html"
    model = Prueba
    context_object_name = "lista"


class PruebaCreateView(CreateView):
    template_name = "home/add.html"
    model = Prueba
    # ver la validacion en el archivo forms.py
    form_class = PruebaForm
    success_url = reverse_lazy("persona_app:exito")


class ResumeFoundationView(TemplateView):
    template_name = "home/resume_foundation.html"

empleado/templates/departamento/home.html
<h1>ESTE ES EL HOME DE DEPARTAMENTO</h1>

empleado/templates/departamento/lista.html
{% extends 'includes/base.html' %}


{% block title %}
    Lista Departamentos
{% endblock title %}



{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                        <tr>
                            <td>
                                {{departamento.name}}
                            </td>
                            <td>
                                {{departamento.shot_name}}
                            </td>
                            <td>
                                <a href="{% url 'persona_app:empleados_area' departamento.shot_name %}" class="button warning"> Ver Empleados </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}
    

empleado/templates/departamento/new_departamento.html
{% extends 'includes/base.html' %}


{% block title %}
    Registrar Departamento
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <form method="post" class="cell callout grid-x grid-margin-x"> {% csrf_token %}
                <div class="medium-6 cell">
                    <label>
                        Apellido:
                        {{ form.apellido }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>
                        Nombre:
                        {{ form.nombre }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>
                        Departamento:
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="medium-6 cell">
                    <label>
                        Short Name:
                        {{ form.shortname }}
                    </label>
                </div>
                <div class="medium-12 cell">
                    <button type="submit"  class="button"> Guardar</button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}